name: laravel-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_sqlite
          tools: composer:v2

      - name: Cache composer
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Prepare .env (sqlite)
        run: |
          cp .env.example .env
          php -r "file_put_contents('database/database.sqlite','');"
          php artisan key:generate
          php -r "
            \$env = file_get_contents('.env');
            \$env = preg_replace('/^DB_CONNECTION=.*/m','DB_CONNECTION=sqlite',\$env);
            \$env = preg_replace('/^DB_DATABASE=.*/m','DB_DATABASE='.getcwd().'/database/database.sqlite',\$env);
            file_put_contents('.env', \$env);
          "
          php artisan migrate --force

      - name: PHPUnit
        run: php artisan test --colors=always
